### ISSUE TITLE
Card ofertas semanales 

### ISSUE THREAD

**Issue by NicoGonzalez1294** [CesarPetit21480/proyecto_final_Rocket#6]
Las card cuenta con la etiqueta "a href", dicha etiqueta se utiliza si queremos redirigir a algún lugar cliqueando sobre las mismas. Si las card solo cumplen la funcion de informar de las ofertas , es recomendable que al hacer click redirijan a un lugar donde se obtenga mas información o de caso contrario a una page 404. 
![image](https://github.com/user-attachments/assets/4d328a5d-55b9-402a-8bee-6e2186b5fbb7)
Cualquier cosita pueden contactarme por el slack de RollingCode

**Comment by CesarPetit21480** [comment]
hola nico te paso el nuevo link corregido el bug https://equiporocketv50.netlify.app<https://equiporocketv50.netlify.app/>
________________________________
De: NicoGonzalez1294 ***@***.***>
Enviado: miércoles, 20 de noviembre de 2024 18:44
Para: CesarPetit21480/proyecto_final_Rocket ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [CesarPetit21480/proyecto_final_Rocket] Card ofertas semanales (Issue #6)


Las card cuenta con la etiqueta "a href", dicha etiqueta se utiliza si queremos redirigir a algún lugar cliqueando sobre las mismas. Si las card solo cumplen la funcion de informar de las ofertas , es recomendable que al hacer click redirijan a un lugar donde se obtenga mas información o de caso contrario a una page 404.
image.png (view on web)<https://github.com/user-attachments/assets/4d328a5d-55b9-402a-8bee-6e2186b5fbb7>
Cualquier cosita pueden contactarme por el slack de RollingCode
